### PR TITLE
TASK: Declare compatible with Neos 5

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
The package works fine with Neos.Ui 5.1.4, so I think this is safe :)

**Comment by mficzel** [comment]
I would love this aswell

**Comment by kdambekalns** [comment]
@dimaip Could you have a look here, please? ❤️

**Review by dimaip — APPROVED** [review]

**Comment by dimaip** [comment]
Ouch, missed it! Sorry guys!

**Comment by kdambekalns** [comment]
Thanks @dimaip! Now… we just need a new release. 😬

**Pull request merged**
